[package]
name = "eris-chain-shared"
version = "1.2.2"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2018"
description = "Liquid staking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://www.erisprotocol.com"
repository = "https://github.com/erisprotocol/contracts-kujira"

[dependencies]
cosmwasm-std =  { version = "1.1.3", features = ["stargate"] }
cosmwasm-schema = "1.1.3"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }

