[package]
name = "eris"
version = "1.6.0"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2018"
description = "Liquid staking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://www.erisprotocol.com"
repository = "https://github.com/erisprotocol/contracts-kujira"

[dependencies]
cosmwasm-std = { version = "1.1.3", features = ["stargate"] }
cosmwasm-schema = "1.1.3"
cw20 = "0.13.2"
cw20-base = { version = "0.13.2", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
eris-chain-adapter = { path = "../eris-chain-adapter" }
astroport = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "3b44a4044b823a145730f66ffaf7ae4205b2cd35" }
