[package]
name = "eris-terra"
version = "1.2.3"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2018"
description = "Liquid staking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://www.erisprotocol.com"
repository = "https://github.com/erisprotocol/contracts-kujira"

[dependencies]
cosmwasm-std = { version = "1.1.3", features = ["stargate"] }
cosmwasm-schema = "1.1.3"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
eris-chain-shared = { path = "../eris-chain-shared" }
osmosis-std-derive = "0.13.2"
cw20 = "1.1.0"
prost = { version = "0.11.0", default-features = false, features = [
    "prost-derive",
] }
prost-types = { version = "0.11.1", default-features = false }
astroport = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "3b44a4044b823a145730f66ffaf7ae4205b2cd35" }
# terra-proto-rs = { version = "4.0.1", default-features = false }
